### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by AlvaroMartinFernandez** [4GeeksAcademy/AdrianAlarcon-LandingReact#1]
Te dejo un par de correcciones de estilos y responsive:

- [x] En la vista mvl las card estan pegadas 
<img width="340" alt="image" src="https://github.com/4GeeksAcademy/AdrianAlarcon-LandingReact/assets/91843474/f1a37992-101b-4b9e-818c-eadfde41c69a">

- [x] en la vista de tablets y pantallas pequeñas 1024 las cartas se sobreponen y el nav se corta 
<img width="416" alt="image" src="https://github.com/4GeeksAcademy/AdrianAlarcon-LandingReact/assets/91843474/c3e7a132-0f3c-4f37-a31e-f86065da2997">

**Comment by AlvaroMartinFernandez** [comment]
Buenas Adrian, el footer esta por encima de las cartas en todas las vistas se corta el boton y en la del mvl el ultimo boton no se ve,  ademas en la vista de la tablet el boton de la primera card tiene mas tamaño debido a que el la cabecera de la carta ocupa 1 linea y no dos como el resto, revisalo y corrige estas cosillas porfa

**Comment by COCOASOO** [comment]
hecho creo
